// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdtjhhzyeumgwnnlnqmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdGpoaHp5ZXVtZ3dubmxucW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTI4NjIsImV4cCI6MjA2MzkyODg2Mn0.vTkY9af1Ey36FH1ZLfT1ST_qlpAS0Fdo7I63OxY6rbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);